# Generated by Django 3.2.5 on 2022-05-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='hardwareProblem',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='softwareProblem',
        ),
        migrations.AddField(
            model_name='pc',
            name='labID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewdata.lab'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pc',
            name='pcID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BrokenPC',
            fields=[
                ('pcID', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('softwareProblem', models.BooleanField(default=False)),
                ('hardwareProblem', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=150)),
                ('date', models.DateField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewdata.pc')),
            ],
        ),
    ]
