# Generated by Django 3.2.5 on 2022-05-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0002_auto_20220524_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='labID',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='newPC',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='pcNumber',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='repairedPC',
        ),
        migrations.AddField(
            model_name='lab',
            name='PC',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='viewdata.pc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='broken',
            field=models.BooleanField(default=False),
        ),
    ]
