# Generated by Django 3.2.5 on 2022-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0004_auto_20220524_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='pcID',
        ),
        migrations.AddField(
            model_name='pc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='pcNumber',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
