# Generated by Django 4.0.4 on 2022-05-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0008_lab_brokenpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenpc',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='PC',
        ),
    ]
