# Generated by Django 4.0.4 on 2022-05-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0009_remove_brokenpc_problem_remove_lab_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenpc',
            name='pcID',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='pcNumber',
        ),
        migrations.AddField(
            model_name='brokenpc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='pcID',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='pc_labID',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pc',
            name='broken',
            field=models.BooleanField(),
        ),
    ]
