# Generated by Django 4.0.4 on 2022-05-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0010_remove_brokenpc_pcid_remove_pc_id_remove_pc_pcnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenpc',
            name='id',
        ),
        migrations.AddField(
            model_name='brokenpc',
            name='BrokenID',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
