# Generated by Django 4.0.4 on 2022-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0013_lab_id_alter_lab_labid'),
    ]

    operations = [
        migrations.CreateModel(
            name='newLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(max_length=45, null=True)),
                ('labID', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('buildingNum', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('floorNum', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('numOfPC', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('numberOfChair', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('labCapacity', models.DecimalField(decimal_places=0, max_digits=4, null=True)),
                ('Status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
