# Generated by Django 4.0.4 on 2022-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0014_newlab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(max_length=45)),
                ('labID', models.DecimalField(decimal_places=0, max_digits=10)),
                ('buildingNum', models.DecimalField(decimal_places=0, max_digits=3)),
                ('floorNum', models.DecimalField(decimal_places=0, max_digits=3)),
                ('numOfPC', models.DecimalField(decimal_places=0, max_digits=3)),
                ('numberOfChair', models.DecimalField(decimal_places=0, max_digits=3)),
                ('labCapacity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='newLab',
        ),
    ]
