# Generated by Django 4.0.4 on 2022-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0016_remove_laboratory_id_alter_laboratory_labid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='buildingNum',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='floorNum',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='labCapacity',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='labName',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='numOfPC',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='numberOfChair',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
