# Generated by Django 4.0.4 on 2022-05-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0017_alter_laboratory_status_alter_laboratory_buildingnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='labID',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
