# Generated by Django 4.0.4 on 2022-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0021_alter_pc_new_alter_pc_pc_labid_alter_pc_repaired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='pcID',
        ),
        migrations.AddField(
            model_name='pc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
