# Generated by Django 4.0.4 on 2022-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0024_remove_pc_pcid_pc_pc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='new2',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
