# Generated by Django 4.0.4 on 2022-05-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0025_pc_new2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='new2',
        ),
    ]
