# Generated by Django 4.0.4 on 2022-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0032_pc_delete_newpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='pc_ID',
        ),
        migrations.AddField(
            model_name='pc',
            name='pcID',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
