# Generated by Django 4.0.4 on 2022-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0033_remove_pc_pc_id_pc_pcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='id',
        ),
        migrations.AlterField(
            model_name='pc',
            name='pcID',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
