# Generated by Django 4.0.4 on 2022-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0036_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='pcID',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
