# Generated by Django 4.0.4 on 2022-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0039_delete_computer_brokenpc_labid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenpc',
            name='LabId',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='brokenpc',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='brokenpc',
            name='description',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='brokenpc',
            name='hardwareProblem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brokenpc',
            name='softwareProblem',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brokenpc',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
