# Generated by Django 4.0.4 on 2022-05-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0040_alter_brokenpc_labid_alter_brokenpc_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenpc',
            name='status',
        ),
    ]
