# Generated by Django 4.0.4 on 2022-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0041_remove_brokenpc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenpc',
            name='BrokenID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
