# Generated by Django 4.0.4 on 2022-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0042_alter_brokenpc_brokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenpc',
            name='ProblemType',
            field=models.CharField(choices=[('Software1', 'Software1'), ('Hardware1', 'Hardware1')], default='Active', max_length=20),
        ),
    ]
