# Generated by Django 4.0.4 on 2022-05-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0044_remove_brokenpc_hardwareproblem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenpc',
            name='ProblemType',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], default='Software1', max_length=20, null=True),
        ),
    ]
