# Generated by Django 4.0.4 on 2022-05-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewdata', '0046_alter_brokenpc_problemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokenpc',
            name='ProblemType',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], max_length=50),
        ),
    ]
